name: CI

on: pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OCaml setup
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.1

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build project
        run: make build

      - name: Test code
        run: make coverage

